---
title: "benchmark_roc"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ampir)
library(caret)
library(tidyverse)
library(pROC)

#devtools::install_github('ejanalysis/analyze.stuff')
library(analyze.stuff)
source("R/calc_cm_metrics.R")
```

```{r}
#read ampir trained model 
svm_Radial98_final <- readRDS("ampir_0.1.0_data/svm_Radial98_final.rds")

#read ampir data

# protein sequence format
bg_tg98 <- readRDS("ampir_0.1.0_data/bg_tg98.rds")
#calculated  features
features98 <- readRDS("ampir_0.1.0_data/features98.rds")
#features split in train and test set 
featuresTest98Nov19 <- readRDS("ampir_0.1.0_data/features98TestNov19.rds")
featuresTrain98Nov19 <- readRDS("ampir_0.1.0_data/features98TrainNov19.rds")
```


```{r}
#subset testfeatures to 1000
testIndex1 <-createDataPartition(y=featuresTest98Nov19$Label, p=.502, list = FALSE)
featuresTest98_1000 <-featuresTest98Nov19[testIndex1,]

#make fasta formatable file
test_1000 <- bg_tg98[bg_tg98$seq_name %in% featuresTest98_1000$seq_name,]
rownames(test_1000) <- NULL

df_to_faa(test_1000[,-3], "ampir_0.1.0_data/1000_test_sqns98_new.fasta")

```

```{r}
#for iamp2L can only use 500 sequences at a time

test_500_bg <- filter(test_1000, Label == "Bg")
test_500_tg <- filter(test_1000, Label == "Tg")

df_to_faa(test_500_bg[,-3], "ampir_0.1.0_data/500_test_sqns98_bg.fasta")
df_to_faa(test_500_tg[,-3], "ampir_0.1.0_data/500_test_sqns98_tg.fasta")

```

```{r}
# full test
test_pred_full <- predict(svm_Radial98_final, featuresTest98Nov19)
confusionMatrix(test_pred_full, featuresTest98Nov19$Label, mode = "everything")

test_pred_full_prob <- predict(svm_Radial98_final, featuresTest98Nov19, type = "prob")
test_pred_full_prob$actual <- featuresTest98Nov19$Label

roc(featuresTest98Nov19$Label, test_pred_full_prob$Tg) 

#saveRDS(test_pred_full_prob, "cache/ampir_prob_data.rds")

#test ampir on 1000 subset
test_pred_1000 <- predict(svm_Radial98_final, featuresTest98_1000)
confusionMatrix(test_pred_1000, featuresTest98_1000$Label, mode = "everything")

#probability test output
ampir_1000 <- predict(svm_Radial98_final, featuresTest98_1000, type = "prob")

#add actual (true values) column
ampir_1000$actual <- featuresTest98_1000$Label

# calculate metrics
ampir_roc_1000 <- as.data.frame(t(sapply(seq(0.01, 0.99, 0.01), calc_cm_metrics, ampir_1000)))

```


```{r}
# ampscanner November 2019

#read in amp scanner prediction results from the test set 
amp_scanner1000_results <- read.csv("raw_data/amp_scannerresultsNov19.csv")

amp_scanner1000_results <- amp_scanner1000_results %>%
  rename("Tg" = "Prediction_Probability") %>%
  mutate(Bg = 1 - Tg) %>%
  add_column(actual = featuresTest98_1000$Label) %>%
  select(Bg, Tg, actual)

# calculate metrics
amp_scanner_roc  <- as.data.frame(t(sapply(seq(0.01, 0.99, 0.01), calc_cm_metrics, amp_scanner1000_results)))

```


```{r}
#results from iamppred website from 1000 test proteins
amppred_1000 <- read.csv("raw_data/iamppredresults.csv")

amppred_1000 <- amppred_1000[,-1]

amppred_1000  <- amppred_1000 %>%
  mutate(Tg = rowMaxs(amppred_1000[2:4])) %>%
  mutate(Bg = 1 - Tg) %>%
  add_column(actual = featuresTest98_1000$Label) %>%
  select(Bg, Tg, actual)

#calculate metrics
amppred_1000_roc <- as.data.frame(t(sapply(seq(0.01, 0.99, 0.01), calc_cm_metrics, amppred_1000)))

```

```{r}
 # ampep november 2019

ampep_1000_results <- read.csv("raw_data/ampepresultsNov19.csv")

ampep_1000_results <- ampep_1000_results %>%
  rename("Tg" = "score") %>%
  mutate(Bg = 1 - Tg) %>%
  add_column(actual = featuresTest98_1000$Label) %>%
  select(Bg, Tg, actual)

#calculate metrics
ampep_1000_roc <- as.data.frame(t(sapply(seq(0.01, 0.99, 0.01), calc_cm_metrics, ampep_1000_results)))
  
```

```{r}
#add model name for
amp_scanner_roc$model <- "amp_scanner"
ampir_roc_1000$model <- "ampir"
amppred_1000_roc$model <- "iamppred"
ampep_1000_roc$model <- "ampep"

#bind model results
models_roc <- rbind(amp_scanner_roc, ampir_roc_1000, amppred_1000_roc, ampep_1000_roc)

# calculate area under the curves for each model 
roc(featuresTest98_1000$Label, ampir_1000$Tg) #0.9649 ampir

roc(featuresTest98_1000$Label, amppred_1000$Tg)  #0.5856 iammpred

roc(featuresTest98_1000$Label, amp_scanner1000_results$Tg)  #0.8655 ampscanner

roc(featuresTest98_1000$Label, ampep_1000_results$Tg) #0.6707
```



```{r}
# plot
ggplot(models_roc) + 
  geom_line(aes(x = FPR, y = Recall, colour = model)) + 
  xlim(0,1) +
  labs(x = "False positive rate", y = "True positive rate") +
  scale_colour_manual(name= "Model and AUC",
                      breaks= c("ampir", "amp_scanner", "ampep", "iamppred"),
                      labels=c("ampir - 96%", "amp scanner - 86%", "ampep - 67%", "iamppred - 58%"),
                      values = c("blueviolet", "goldenrod2", "blue4", "cyan")) +
  theme(legend.position = c(0.8, 0.31),
        legend.key = element_rect(fill = "white"),
        panel.background = element_blank(),
        axis.line = element_line(colour = "grey")) 

ggsave("figures/model_roc.png", height = 100, width = 140, units = "mm")
```
