---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

run after line 400 from 05_benchmark.Rmd
```{r}
genome_rocs %>% mutate(organism = ifelse(organism=="Homo sapiens (Human)","Homo sapiens ","Arabidopsis thaliana")) %>% 
  ggplot() + 
  geom_line(aes(x = FP, y = TP, colour = model),size=1.1) + 
  xlim(0,500) +
#  scale_fill_manual(values=c("#E69F00", "#56B4E9", "#D55E00",  "#CC79A7")) +
  labs(x = "False Positives", y = "True Positives", colour = "") +
  facet_wrap(~organism, scales = "free_y", nrow = 1) + 
  theme(legend.position = "bottom",
        strip.background = element_blank(),
        strip.text = element_text(colour = "white",
                                  face = "italic",
                                  size = 16),
        legend.key = element_blank(),
        legend.text = element_text(color = "grey", size = 12),
        legend.background = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        plot.background=element_rect(fill = "black", colour = NA),
        panel.background = element_rect(fill = "black"),
        axis.line = element_line(colour = "grey"),
        axis.text = element_text(colour="grey", size = 10),
        axis.title = element_text(colour="white", size = 14)) +
   scale_color_manual(values=c("#CC79A7", "#56B4E9", "#D55E00", "#F0E442")) 

ggsave("figure_1_black.png", width = 7, height = 5,dpi = 600)

```

